### PR TITLE
fix(server): mount tun for rootless

### LINKED ISSUE #53: Fix docker capability: rootless dind fails with newuidmap EPERM
## User request
Agents/workloads that enable the **docker** capability (rootless `docker:dind-rootless` sidecar) fail to start. The dind container logs show:

```
newuidmap ... failed: write to uid_map failed: Operation not permitted
```

We need to make the docker-capable agent workloads start reliably.

### Findings
- The workload pod spec is mutated in k8s-runner (not Helm values) when `capabilities: ["docker"]` is requested.
- For the rootless docker implementation, we currently **force** `pod.spec.hostUsers=false`.
- Rootless DinD uses `rootlesskit` + `newuidmap/newgidmap` and subordinate ID ranges.
- When the pod is already in a Kubernetes user namespace (`hostUsers:false`), `newuidmap` commonly fails because it attempts to map UIDs that don’t exist in the parent user namespace, yielding the observed `EPERM` on `/proc/<pid>/uid_map`.
- A secondary potential contributor (cluster policy dependent): `securityContext.allowPrivilegeEscalation=false` / `no_new_privs=1` can prevent `newuidmap` from elevating (setuid/caps), producing the same symptom.

### Required changes
1) **Stop forcing Kubernetes user namespaces for rootless docker workloads**
   - Update `internal/server/capabilities.go` so that for `DockerImplementationRootless` the capability plan does **not** set `pod.spec.hostUsers=false`.
   - Leave `pod.spec.hostUsers` **unset** (`nil`) for this implementation.

2) **Update tests**
   - Update `internal/server/workload_test.go` (e.g. `TestStartWorkloadInjectsDockerRootless`) to expect `pod.Spec.HostUsers == nil`.

### Optional hardening (if needed for certain clusters)
If workloads still fail due to `no_new_privs` / PSS restricted-like settings, consider explicitly setting the rootless sidecar `securityContext` to allow the required privilege gain for `newuidmap` (while keeping the container non-root and minimizing capabilities).

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- add /dev/net/tun hostPath volume + mount for rootless docker sidecar
- guard rootless docker injection against tun volume name conflicts
- extend tests for new tun volume behavior

## Testing
- go test ./...
- go vet ./...

Closes #53

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Summary
- add /dev/net/tun hostPath volume + mount for rootless docker sidecar
- guard rootless docker injection against tun volume name conflicts
- extend tests for new tun volume behavior

## Testing
- go test ./... (passed: 2, failed: 0, skipped: 3)
- go vet ./... (no issues)

File: internal/server/capabilities.go [hunk 1]
```diff
@@ -208,7 +214,17 @@ func dockerVolumes(implementation config.DockerImplementation) []corev1.Volume {
 				EmptyDir: &corev1.EmptyDirVolumeSource{},
 			},
 		}
-		return []corev1.Volume{dataVolume, runVolume}
+		hostPathType := corev1.HostPathCharDev
```
Comment (noa-lucent) [inline internal/server/capabilities.go:217]: [minor] Consider adding a short comment here (or near the constants) explaining *why* we inject a hostPath mount for /dev/net/tun (rootlesskit slirp4netns/vpnkit) and calling out the security/policy implication of hostPath volumes. This will help prevent accidental removal/regression later.

File: internal/server/workload_test.go [hunk 2]
```diff
@@ -652,6 +657,38 @@ func TestStartWorkloadRejectsDockerVolumeNameConflict(t *testing.T) {
 	}
 }
 
+func TestStartWorkloadRejectsDockerTunVolumeNameConflict(t *testing.T) {
```
Comment (noa-lucent) [inline internal/server/workload_test.go:660]: [minor] Test coverage: validateDockerInjection also rejects a rootless volume name conflict for dockerRunVolumeName (docker-run), but we don’t currently have a test for it. Consider making the volume-name-conflict tests table-driven over docker-data/docker-run/docker-tun to keep this area consistent and avoid regressions.

**Review by noa-lucent — APPROVED** [review]
Looks good and matches the updated issue spec: rootless docker sidecar now mounts /dev/net/tun via hostPath, rejects name conflicts, and tests cover the new behavior.\n\nMinor follow-ups in inline comments (docs note + add coverage for docker-run conflict).
