### PR TITLE
fix(server): add legacy seccomp annotations

### LINKED ISSUE #53: Fix docker capability: rootless dind fails with newuidmap EPERM
## User request
Agents/workloads that enable the **docker** capability (rootless `docker:dind-rootless` sidecar) fail to start. The dind container logs show:

```
newuidmap ... failed: write to uid_map failed: Operation not permitted
```

We need to make the docker-capable agent workloads start reliably.

### Findings
- The workload pod spec is mutated in k8s-runner (not Helm values) when `capabilities: ["docker"]` is requested.
- For the rootless docker implementation, we currently **force** `pod.spec.hostUsers=false`.
- Rootless DinD uses `rootlesskit` + `newuidmap/newgidmap` and subordinate ID ranges.
- When the pod is already in a Kubernetes user namespace (`hostUsers:false`), `newuidmap` commonly fails because it attempts to map UIDs that don’t exist in the parent user namespace, yielding the observed `EPERM` on `/proc/<pid>/uid_map`.
- A secondary potential contributor (cluster policy dependent): `securityContext.allowPrivilegeEscalation=false` / `no_new_privs=1` can prevent `newuidmap` from elevating (setuid/caps), producing the same symptom.

### Required changes
1) **Stop forcing Kubernetes user namespaces for rootless docker workloads**
   - Update `internal/server/capabilities.go` so that for `DockerImplementationRootless` the capability plan does **not** set `pod.spec.hostUsers=false`.
   - Leave `pod.spec.hostUsers` **unset** (`nil`) for this implementation.

2) **Update tests**
   - Update `internal/server/workload_test.go` (e.g. `TestStartWorkloadInjectsDockerRootless`) to expect `pod.Spec.HostUsers == nil`.

### Optional hardening (if needed for certain clusters)
If workloads still fail due to `no_new_privs` / PSS restricted-like settings, consider explicitly setting the rootless sidecar `securityContext` to allow the required privilege gain for `newuidmap` (while keeping the container non-root and minimizing capabilities).

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- add legacy AppArmor/seccomp pod annotations for rootless docker sidecar
- ensure rootless workload tests assert legacy annotations

## Testing
- go test ./...
- go vet ./...

Closes #53

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Summary
- add legacy AppArmor/seccomp pod annotations for rootless docker sidecar
- ensure rootless workload tests assert legacy annotations

## Testing
- go test ./... (passed: 2, failed: 0, skipped: 3)
- go vet ./... (no issues)

File: internal/server/workload.go [hunk 1]
```diff
@@ -81,6 +82,11 @@ func (s *Server) StartWorkload(ctx context.Context, req *runnerv1.StartWorkloadR
 	if len(secretNames) > 0 {
 		annotations[secretAnnotationKey] = strings.Join(secretNames, ",")
 	}
+	if capabilityPlan.dockerImplementation == config.DockerImplementationRootless {
```
Comment (noa-lucent) [inline internal/server/workload.go:85]: [minor] This is capability-specific behavior, but StartWorkload now reaches into `capabilityPlan.dockerImplementation` (and pulls in a `config` import). Consider moving this into the capability plan (e.g., `capabilityPlan.applyPodAnnotations(annotations)` or returning required annotations from `apply`) so all docker injection stays centralized.\n\nAlso: a short comment here would help future readers understand why we set *pod-level* seccomp to "unconfined" (it affects all containers) — as a fallback for clusters that ignore container-level settings.

File: internal/server/capabilities.go [hunk 2]
```diff
@@ -28,6 +28,10 @@ const (
 	dockerRootlessRunMountPath    = "/run/user/1000"
 	dockerTunDevicePath           = "/dev/net/tun"
 	dockerPrivilegedDataMountPath = "/var/lib/docker"
+	dockerAppArmorLegacyAnnotationKey = "container.apparmor.security.beta.kubernetes.io/" + dockerSidecarName
```
Comment (noa-lucent) [inline internal/server/capabilities.go:31]: [nit] Please run gofmt on this const block (the new docker annotation/security constants aren’t aligned like the existing ones).

File: internal/server/workload_test.go [hunk 3]
```diff
@@ -455,6 +455,9 @@ func TestStartWorkloadInjectsDockerRootless(t *testing.T) {
 	if pod.Spec.HostUsers != nil {
 		t.Fatalf("expected hostUsers to remain unset for rootless docker")
 	}
+	assertAnnotation(t, pod.Annotations, dockerAppArmorLegacyAnnotationKey, dockerSecurityProfileUnconfined)
```
Comment (noa-lucent) [inline internal/server/workload_test.go:458]: [minor] Along with asserting these annotations for rootless, please add a negative assertion in `TestStartWorkloadInjectsDockerPrivileged` that the legacy seccomp/AppArmor annotations are *not* present. This keeps the security relaxation clearly scoped to the rootless implementation.

**Review by noa-lucent — APPROVED** [review]
Adds the legacy AppArmor + seccomp alpha annotations for rootless docker workloads and updates unit tests accordingly.

Minor follow-ups in inline comments (centralize capability-specific annotation injection, document pod-level seccomp unconfined intent, add a negative assertion for privileged).
