### PR TITLE
fix(server): include kube error details

### LINKED ISSUE #43: Improve error detail in grpcErrorFromKube responses
## User Request

When the k8s-runner encounters Kubernetes API errors (e.g., RBAC `Forbidden`), the gRPC error returned to callers (like the orchestrator) contains only a generic message such as `"permission denied"`. This makes it very hard to diagnose issues — the caller has no idea which resource or operation failed, or which ServiceAccount lacks permission.

The orchestrator log currently shows:
```
reconciler: start workload for agent ...: rpc error: code = PermissionDenied desc = permission denied
```

### Change: Include Kubernetes error detail in gRPC error messages

**File:** `internal/server/errors.go` — `grpcErrorFromKube` function

**Current behavior:** Each `case` in the switch returns a hardcoded generic message (e.g., `"permission denied"`, `"resource not found"`).

**New behavior:** Extract the detailed message from the Kubernetes `StatusError` and include it in the gRPC error message. The Kubernetes `*apierrors.StatusError` type provides `.Status().Message` which contains a full description like:
```
secrets is forbidden: User "system:serviceaccount:agyn-platform:k8s-runner" cannot create resource "secrets" in API group "" in the namespace "agyn-workloads"
```

**Implementation:**

Use `apierrors.ReasonForError(err)` or type-assert to `*apierrors.StatusError` to get the `.Status().Message` field, then include it in the gRPC error description. The simplest approach: for every mapped case, use the Kubernetes status message directly as the gRPC description (it already contains the category + detail). For the `default` case, include `err.Error()`.

Example result for a Forbidden error:
```go
case apierrors.IsForbidden(err):
    return status.Errorf(codes.PermissionDenied, "kubernetes: %s", statusMessage(err))
```

Where `statusMessage` extracts the Kubernetes status message or falls back to `err.Error()`.

**Tests:** Update `internal/server/errors_test.go` (if it exists) or add tests verifying that the gRPC error messages include Kubernetes detail for each mapped error case.

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- include Kubernetes status messages in gRPC error descriptions
- add grpcErrorFromKube coverage for status details
- bump Helm chart version to 0.9.0

## Testing
- CGO_ENABLED=0 go test ./...
- CGO_ENABLED=0 go vet ./...
- CGO_ENABLED=0 go build ./...
- CGO_ENABLED=0 go vet -tags e2e ./test/e2e/

Closes #43

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Summary
- include Kubernetes status messages in gRPC error descriptions
- add grpcErrorFromKube coverage for status details
- bump Helm chart version to 0.9.0

## Test & Lint Summary
Tests:
- CGO_ENABLED=0 go test ./... (passed: 2, failed: 0, skipped: 3)

Lint:
- CGO_ENABLED=0 go vet ./... (no issues)
- CGO_ENABLED=0 go vet -tags e2e ./test/e2e/ (no issues)

Build:
- CGO_ENABLED=0 go build ./...

File: internal/server/errors.go [hunk 1]
```diff
@@ -15,20 +18,43 @@ func grpcErrorFromKube(logger *zap.Logger, err error, fallback codes.Code) error
...
 	default:
-		return status.Error(fallback, "kubernetes request failed")
+		return status.Error(fallback, formatKubeError("kubernetes request failed", message))
+	}
+}
+
+func formatKubeError(base, detail string) string {
+	if detail == "" {
+		return base
 	}
```
Comment (noa-lucent) [inline internal/server/errors.go:47]: [major] The issue specification explicitly requires the `default` case to include `err.Error()` so that non-`StatusError` errors still surface their detail. Currently, when a plain (non-Kubernetes) error reaches the default branch, `kubeStatusMessage` returns `""` and the caller only sees `"kubernetes request failed"` with no context — which is the same opaque-message problem this PR is supposed to fix.

Suggested fix: fall back to `err.Error()` when `kubeStatusMessage` returns empty:

```go
default:
    detail := message
    if detail == "" {
        detail = err.Error()
    }
    return status.Error(fallback, formatKubeError("kubernetes request failed", detail))
```

File: internal/server/errors_test.go [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+			detail := strings.TrimSpace(apiStatus.Status().Message)
+			if detail == "" {
+				t.Fatalf("expected status message detail")
+			}
+			expected := test.base + ": " + detail
+			if st.Message() != expected {
+				t.Fatalf("expected message %q, got %q", expected, st.Message())
+			}
+		})
+	}
```
Comment (noa-lucent) [inline internal/server/errors_test.go:87]: [minor] The table only covers `NotFound` and `Forbidden`. Consider adding cases for the remaining mapped error types (`AlreadyExists`, `Invalid`, `Unauthorized`, `Conflict`) to ensure each code mapping is exercised. Table-driven tests make this trivial — just a few more entries.

File: internal/server/errors_test.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+	st, ok := status.FromError(got)
+	if !ok {
+		t.Fatalf("expected grpc status error")
+	}
+	if st.Code() != codes.Internal {
+		t.Fatalf("expected code %s, got %s", codes.Internal, st.Code())
+	}
+	if st.Message() != "kubernetes request failed" {
+		t.Fatalf("expected fallback message, got %q", st.Message())
+	}
```
Comment (noa-lucent) [inline internal/server/errors_test.go:101]: [minor] This test verifies a non-`APIStatus` error in the default branch, but it asserts the message is `"kubernetes request failed"` (no detail). Once the `default` case is fixed to include `err.Error()` (per the issue spec), update this assertion to expect `"kubernetes request failed: boom"` and add a comment explaining why — to confirm that generic error detail is propagated.

File: charts/k8s-runner/Chart.yaml [hunk 4]
```diff
@@ -2,8 +2,8 @@ apiVersion: v2
 name: k8s-runner
 description: Helm chart for the agynio k8s-runner gRPC service
 type: application
-version: 0.6.0
-appVersion: 0.6.0
+version: 0.9.0
```
Comment (noa-lucent) [inline charts/k8s-runner/Chart.yaml:5]: [nit] Version jumps from 0.6.0 to 0.9.0, skipping 0.7.x and 0.8.x. If those versions were consumed elsewhere (other Helm charts, deployment scripts), this is fine. Otherwise, worth confirming this is intentional and not a typo — 0.7.0 might be more appropriate for a behavioral change.

**Review by noa-lucent — CHANGES_REQUESTED** [review]
The core approach is solid — extracting the Kubernetes status message via `errors.As` and surfacing it in gRPC errors is clean and well-structured. Two items to address:

1. **[major]** The `default` branch drops error detail for non-`StatusError` errors, contradicting the issue requirement to include `err.Error()` in that case. This leaves generic errors just as opaque as before.

2. **[minor]** Test coverage is partial — only 2 of 6 mapped error types are tested, and the fallback test needs updating once the default branch is fixed.

Please address the major item before merge.

File: charts/k8s-runner/Chart.yaml (hunk 4 above)
Comment (rowan-stein) [reply charts/k8s-runner/Chart.yaml:5]: Versions 0.7.0 through 0.8.1 are already published — the Chart.yaml in the repo was not kept in sync with tag-based releases. 0.9.0 is intentional to leapfrog past all existing published versions.

**Comment by casey-brooks** [comment]
## Summary
- preserve non-StatusError details in gRPC error messages
- add coverage for remaining Kubernetes error mappings

## Test & Lint Summary
Tests:
- CGO_ENABLED=0 go test ./... (passed: 2, failed: 0, skipped: 3)

Lint:
- CGO_ENABLED=0 go vet ./... (no issues)
- CGO_ENABLED=0 go vet -tags e2e ./test/e2e/ (no issues)

Build:
- CGO_ENABLED=0 go build ./...

**Review by noa-lucent — APPROVED** [review]
All prior feedback addressed. Verified in code:

1. **`err.Error()` fallback** — Moved above the switch so `message` is always populated. Clean approach that benefits all branches, not just the default. ✅
2. **Full test coverage** — All 6 mapped Kubernetes error types now have table entries exercising both the gRPC code mapping and the detail inclusion. ✅
3. **Fallback test updated** — Asserts `"kubernetes request failed: boom"`, confirming non-`APIStatus` error detail propagates. ✅
4. **Chart version** — 0.9.0 confirmed intentional per Rowan's explanation. ✅

LGTM — clean, well-tested, and resolves #43.
